apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-003
spec:
  selector:
    matchLabels:
      app: nginx-container-003
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-container-003
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-003
  labels:
    app: nginx
spec:
  ports:
  - nodePort: 30003
    port: 80
    protocol: TCP
  selector:
    app: nginx-container-003
  type: NodePort
 
